name: AzipediaSearcher
version: '1.2.1'
main: net.azisaba.albardoo02.AzipediaSearcher
api-version: '1.15'
author: albardoo02
website: https://github.com/AzisabaNetwork/AzipediaSearcher

commands:
  wiki:
    description: "Wiki検索コマンド"
    aliases:
    - azipedia
    - azisabawiki
    - officialwiki

permissions:
  azipediasearcher.command.wiki:
    default: op
  azipediasearcher.command.bypass:
    default: op